version: "3.9"
services:
#  nginx-proxy:
#    image: nginxproxy/nginx-proxy
#    container_name: nginx-proxy
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./docker-web/certs:/etc/nginx/certs
#      - ./docker-web/vhost:/etc/nginx/vhost.d
#      - ./examples/chat2/build:/usr/share/nginx/html
#      - /var/run/docker.sock:/tmp/docker.sock:ro

#  proxy-acme:
#    image: nginxproxy/acme-companion
#    container_name: nginx-proxy-acme
#    volumes_from:
#      - nginx-proxy
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#      - ./docker-web/acme:/etc/acme.sh

  web:
    build:
      context: ../..
      dockerfile: chat/Dockerfile
    container_name: pistol-web
    ports:
      - "3000:3000"

#    environment:
#      - NGINX_HOST=pistol.bulldoginfo.com
#      - NGINX_PORT=80

  testnet:
    build:
      context: ../..
      dockerfile: testnet/Dockerfile
    container_name: pistol-testnet
    ports:
      - "11110:11110"
      - "11111:11111"
